# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/ewsnybchan7/Infinity-Scroll-View
    rev: V3.2.0
    hooks:
    -   id: test-commit